snowflake:
  role: "PARTICIPANT"
  warehouse: "COMPUTE_WH_PARTICIPANT"
  database: null
  schema: null

mysql_sy_test:
  host: "sycommu_mysql_HOST"
  port: "sycommu_mysql_PORT"
  user: "test"
  password: "sycommu_mysql_PASSWORD"
  database: "sy_community_link"


llm:
  default_model: "deepseek_chat"

  models:
    deepseek_reason:
      api_key_env: "API_KEY_Lab_DeepSeek"
      base_url_env: "BASE_URL_Lab_DeepSeek"
      model: "deepseek-reasoner"
      temperature: 0.1
      top_p: 0.95
      timeout: 600.0
      max_retries: 2
      max_completion_tokens: 65535
      max_concurrency: 8
      default_system_prompt: ""

    deepseek_chat:
      api_key_env: "API_KEY_Lab_DeepSeek"
      base_url_env: "BASE_URL_Lab_DeepSeek"
      model: "ep-20260426182751-8k5s5"
      temperature: 0.1
      top_p: 0.95
      timeout: 600.0
      max_retries: 2
      max_completion_tokens: 65535
      max_concurrency: 8
      default_system_prompt: ""  

    deepseek_v4_flash:
      api_key_env: "API_KEY_DeepSeek_v4_flash"
      base_url_env: "BASE_URL_DeepSeek_v4_flash"
      model: "deepseek-v4-flash"
      temperature: 0.1
      top_p: 0.95
      timeout: 600.0
      max_retries: 2
      max_completion_tokens: 65535
      max_concurrency: 8
      default_system_prompt: ""  

    deepseek_chat_personal:
      api_key_env: "API_KEY_Personal_Volces"
      base_url_env: "BASE_URL_Personal_Volces"
      model: "deepseek-v3-2-251201"
      temperature: 0.1
      top_p: 0.95
      timeout: 600.0
      max_retries: 2
      max_completion_tokens: 65535
      max_concurrency: 8
      default_system_prompt: ""  
   


engine:
  default_provider: "reforce"

  providers:
    reforce:
      root: "../../ReFoRCE"
      spider2_root: "../../ReFoRCE/spider2-snow"
      nl2sql_script: "../../ReFoRCE/methods/ReFoRCE/online_nl2sql.py"
      schema_linking_script: "../../ReFoRCE/methods/ReFoRCE/online_schema_linking.py"
    reforce_gen_sl_m1:
      root: "../../ReFoRCE"
      spider2_root: "../../ReFoRCE/spider2-snow"
      nl2sql_script: "../../ReFoRCE/methods/ReFoRCE/online_nl2sql_gen_sl_m1.py"
      schema_linking_script: "../../ReFoRCE/methods/ReFoRCE/online_schema_linking.py"
